---
title: "Notice Scripts"
author: "Ariane"
date: "27 janvier 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Files in the *Scripts* file are annotated .R files corresponding to the production of database and subsequent plots of the whole plot article.
Files in the *DB* are the initial inventories and produced database.


## DB file

- *Alpha_Plots*: Alpha matrices for the Dirichlet sampling of the vernacular names botanical trials. 
It is a list of plot-specific matrices, following previous investigation suggesting that botanical associations should rely on local community inventories and history to minimize biases.

- *Paracou_R_Subdivided_ok*: Formatted Paracou inventories, it contains various matrices and lists that are not all used here. 
*LivingStand_all* is the lists used here, inventories are subdivided by inventoried year and by plot.

- *BotanyGenus*: Botanical correspondence tables to associate genuses to botanical names trialed from vernacular names.

- *BridgeOK.csv*: csv file of the Bridge dataset: 6 leaves and 2 stem traits.

- *DataLifeTraits.csv*: csv file for the Hmax and seed mass class.

- *TaxoComposition_ForGraphs*: Coordinates of inventories and plots in the 2 dimensions space from taxonomic composition NMDS. 
Lists the coordinates along the various iteration: for now on, only 5 repetitions (becaus run locally). **Figure 1 & 2 (a)**.

- *FunctionalComposition_forGraphs*: Coordinates of inventories and plots in the 2 dimensions space from functional composition NMDS. 
Lists the coordinates along the 50 iteration. Comes from the script: *FunctionalNMDS.R*. **Figure 1 & 2 (b)**.

- *ReplacementTraj_ForGraphs*: List by treatment of plots Richness, Shannon and Simpson diversity along inventoried year. 
It gives the 0.025, 0.5 and 0.975 quantiles from 50 repetitions.
Comes from the script: *ReplacementTraj_ForGraphs.R*. **Figure 3**.

- *FunctionalTraj_ForGraphs*: List by treatment of plots Rao diversity along inventoried year. 
It gives the 0.025, 0.5 and 0.975 quantiles from *only 5 for now* repetitions. **Figure 4**.


## Scripts file

- *Vernacular_handle.R*: General functions, to propagate taxonomic uncertainty.

- *TraitsMiceFilling.R*: General functions, gap-filling of the traits database.

- *Functional NMDS.R*: Functional composition analysis: iterative NMDS on plots functional inventories.

- *DivTaxo_trajectories.R*: Taxonomic Richness, Shannon and Simpson diversity trajectories per plot along inventoried years.

- *DrawingTools.R*: To alleviate the *Manuscript* file I defined separately the functions to draw the plots from dataset.
